"""empty message

Revision ID: 243cbf9890d2
Revises: 
Create Date: 2019-09-02 13:34:25.945645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243cbf9890d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'created_by')
    # ### end Alembic commands ###
